module.exports = {
    SUCCESSFUL: 200,
    BAD_REQUEST: 400,
    NOT_FOUND: 404,
    INTERNAL_SERVER_ERROR: 500,
    TOO_MANY_REQUESTS: 429,
    BAD_GATEWAY: 502,
    GATEWAY_TIMEOUT: 504,
    METHOD_NOT_ALLOWED: 405,
    NOT_ACCEPTABLE: 406,
    UNAUTHORIZED: 401,
    LIMIT_EXCEEDED: 201,

    LIMIT_EXCEEDED_MSG: 'Limit exceeded.',
    VERIFICATION_REQUIRED_MSG: 'Your email address is not verified. Please verify your email to access full features.',
    FILE_UPLOAD: 'File uploaded successfully.',
    FILE_DELETE: 'File deleted successfully.',
    PROFILE_PHOTO: 'Profile picture uploaded successfully.',
    CONTACT_US_MSG: 'Your message has been sent successfully. We will contact you very soon!',
    DASHBOARD: 'Dashboard',
    USER_ALREADY_VERIFIED: 'Your account has already been verified. Please log in.',
    NO_TOKEN: 'Please provide authentication token.',
    PERMISSION_DENIED: `You don't have permission for this action.`,
    INVALID_MSG: 'Invalid credentials. Please use correct API key and API key secret.',
    UNAUTHORIZED_MSG: 'Unauthorized. Please use correct email and password combination.',
    OLD_PASSWORD_MSG: 'Please enter a valid old password.',
    Login_MSG: 'Logged in successfully.',
    Logout_MSG: 'Logged out successfully.',
    NOT_FOUND_MSG: 'Not found.',
    FORGOT_PASSWORD: 'Reset password link sent successfully to your email address.',
    CHANGE_PASSWORD: 'Password changed successfully.',
    INVALID_REQUEST: 'You are not authorized for this request',

    ACCOUNT_DEACTIVATE: 'Your account appears to be deactivated.',
    ACCOUNT_DELETE: 'Your profile is deleted from admin panel kindly mail us at info@omnisttechhub.com or call us at 7417773034.',
    // USER_NOT_FOUND: `Sorry, we couldn't find an account with that email.`,

    USER_NOT_FOUND: 'User details not found.',
    USER_LIST: 'User list retrieved successfully.',
    USER_DETAILS: 'User details retrieved successfully.',
    USER_STATUS_INACTIVE: 'User status set to inactive successfully.',
    USER_STATUS_ACTIVE: 'User status set to active successfully.',
    USER_NAME_ALREADY_EXISTS: 'The username already exists. Please use a different name.',
    USER_EMAIL_ALREADY_EXISTS: 'The email already exists. Please use a different email.',
    USER_UPDATE: 'User information has been updated successfully.',
    USER_CREATE: `Registration successful! We have sent a verification link to your email. Please check your inbox and spam folder. If you haven't received the email, please click the 'Resend Verification Link' button below.`,
    USER_EMAIL_VERIFY: 'Email verification link sent successfully to your email address',
    USER_EMAIL_VERIFY_MSG: 'Your email has been successfully verified. Thank you for verifying your email. You can now access all the features of our website.',
    USER_EMAIL_VERIFY_FAIL: 'An error occurred while verifying your email. Please try again later or contact support for assistance.',
    USER_RESEND_VERIFICATION_LINK: `A new verification link has been sent to your email address. Please check your inbox and follow the instructions to verify your email. Please check your email inbox for the verification link. If you don't see it in your inbox, please also check your spam or promotions folder.`,

    COMPANY_NOT_FOUND: 'Company not found.',
    COMPANY_LIST: 'List of company users retrieved successfully.',
    COMPANY_DETAILS: 'Details of company user retrieved successfully.',
    COMPANY_STATUS_INACTIVE: 'Company status set to inactive successfully.',
    COMPANY_STATUS_ACTIVE: 'Company status set to active successfully.',
    COMPANY_NAME_ALREADY_EXISTS: 'The company name already exists. Please use a different name.',
    COMPANY_CIN_ALREADY_EXISTS: 'The company cin already exists. Please use a different cin.',
    COMPANY_LLPIN_ALREADY_EXISTS: 'The company llpin already exists. Please use a different cin.',
    COMPANY_FCIN_ALREADY_EXISTS: 'The company fcin already exists. Please use a different cin.',
    COMPANY_GST_ALREADY_EXISTS: 'The company gst already exists. Please use a different gst.',
    COMPANY_PAN_ALREADY_EXISTS: 'The company pan already exists. Please use a different pan.',
    COMPANY_MOBILE_ALREADY_EXISTS: 'The company mobile number already exists. Please use a different email.',
    COMPANY_EMAIL_ALREADY_EXISTS: 'The company email already exists. Please use a different email.',
    COMPANY_UPDATE: 'Company information updated successfully.',
    COMPANY_CREATE: 'Company information created successfully.',

    ADMIN_STAFF_LIST: 'Staff List',
    ADMIN_NOT_FOUND: 'Not found',
    ADMIN_STAFF_DETAILS: 'Staff details',
    ADMIN_STAFF_STATUS_DELETE: 'Staff member deleted successfully',
    ADMIN_STAFF_STATUS_INACTIVE: 'The status of the staff is inactive successful',
    ADMIN_STAFF_STATUS_ACTIVE: 'The status of the staff is active successful',
    ADMIN_STAFF_NAME_ALREADY_EXISTS: 'Name is already exists. Please use a different name',
    ADMIN_STAFF_EMAIL_ALREADY_EXISTS: 'The email is already exists. Please use a different email',
    ADMIN_STAFF_MOBILE_ALREADY_EXISTS: 'Mobile number is already exists. Please use a different mobile number',
    ADMIN_STAFF_UPDATE: 'Information has been successfully updated',
    ADMIN_STAFF_CREATE: 'Information has been successfully created',

    ADMIN_COMPANY_NOT_FOUND: 'Company not found',
    ADMIN_COMPANY_LIST: 'Company user List',
    ADMIN_COMPANY_DETAILS: 'Company user details',
    ADMIN_COMPANY_STATUS_INACTIVE: 'The status of the company is inactive successful',
    ADMIN_COMPANY_STATUS_ACTIVE: 'The status of the company is active successful',
    ADMIN_COMPANY_NAME_ALREADY_EXISTS: 'The company name is already exists. Please use a different name',
    ADMIN_COMPANY_UPDATE: 'Company information has been successfully updated',
    ADMIN_COMPANY_CREATE: 'Company information has been successfully created',

    FAQ_LIST: 'FAQ list loaded successfully',
    FAQ_CREATE: 'FAQ created successfully',
    FAQ_QUESTION_ALREADY_EXISTS: 'FAQ question is already exists.',
    FAQ_DELETE: 'FAQ deleted successfully',
    FAQ_UPDATE: 'FAQ updated successfully',
    FAQ_NOT_FOUND: 'FAQ Details not found',
    FAQ_DETAILS: 'Details',

    BLOG_LIST: 'Blog list loaded successfully',
    BLOG_CREATE: 'Blog created successfully',
    BLOG_TITLE_ALREADY_EXISTS: 'Blog title is already exists.',
    BLOG_DELETE: 'Blog deleted successfully',
    BLOG_UPDATE: 'Blog updated successfully',
    BLOG_NOT_FOUND: 'Blog Details not found',
    BLOG_DETAILS: 'Details',

    REVIEW_LIST: 'Review list loaded successfully',
    REVIEW_CREATE: 'Review created successfully',
    REVIEW_QUESTION_ALREADY_EXISTS: 'Review question is already exists.',
    REVIEW_DELETE: 'Review deleted successfully',
    REVIEW_UPDATE: 'Review updated successfully',
    REVIEW_NOT_FOUND: 'Review Details not found',
    REVIEW_DETAILS: 'Details',

    CONTACT_LIST: 'CONTACT list loaded successfully',
    CONTACT_CREATE: 'Your request has been received. We will connect with you shortly.',
    CONTACT_DELETE: 'CONTACT deleted successfully',
    CONTACT_UPDATE: 'CONTACT updated successfully',
    CONTACT_NOT_FOUND: 'CONTACT Details not found',
    CONTACT_DETAILS: 'Details',


    INDUSTRY_NOT_FOUND: 'No industry record found',
    INDUSTRY_LIST: 'Industry list',
    INDUSTRY_DETAILS: 'Industry details',
    INDUSTRY_STATUS_DELETE: 'Industry has been deleted successfully',
    INDUSTRY_STATUS_INACTIVE: 'Industry status has been set to inactive successfully',
    INDUSTRY_STATUS_ACTIVE: 'Industry status has been set to active successfully',
    INDUSTRY_NAME_ALREADY_EXISTS: 'The name already exists. Please use a different name',
    INDUSTRY_DISPLAYNAME_ALREADY_EXISTS: 'The display name already exists. Please use a different display name',
    INDUSTRY_EMAIL_ALREADY_EXISTS: 'The email already exists. Please use a different email',
    INDUSTRY_UPDATE: 'Industry information has been updated successfully',
    INDUSTRY_CREATE: 'Industry information has been created successfully',

    CATEGORY_NOT_FOUND: 'Category not found',
    FILE_UPLOAD: 'File uploaded successfully',
    CATEGORY_LIST: 'Category List',
    CATEGORY_DETAILS: 'Category details',
    CATEGORY_STATUS_DELETE: 'Category is deleted successfully',
    CATEGORY_STATUS_INACTIVE: 'The status of the Category is inactive successful',
    CATEGORY_STATUS_ACTIVE: 'The status of the Category is active successful',
    CATEGORY_NAME_ALREADY_EXISTS: 'Category name is already exists. Please use a different name',
    CATEGORY_UPDATE: 'Category information has been successfully updated',
    CATEGORY_CREATE: 'Category information has been successfully created',
    CATEGORY_NOT_DISABLE: 'You can not disable this category because this category already connected with subcategories and products',

    DATA_NOT_FOUND: 'No record found',
    // ticket constants
    TICKET_RAISED: "Ticket raised successfully",
    TICKET_UPDATED: "Ticket updated successfully",
    TICKET_REPLY: "Ticket replied successfully",
    TICKET_NOT_FOUND: "Ticket not found",
    TICKET_LIST: "Ticket List",


    NO_SUBSCRIPTION: "Subscription not found",
    CANCEL_SUBSCRIPTION: "Subscription canceled successfully",
    BUY_SUBSCRIPTION: "Subscription bought successfully",
    SUBSCRIPTION_LIST: "Subscription List",


    SERVICE_CREATED: "Service created successfully",
    SERVICE_LIST: "Service List",
    SERVICE_UPDATE: "Service updated successfully",
    SERVICE_NOT_FOUND: "Service not found",
    SERVICE_DELETED: "Service deleted successfully",


    PLAN_CREATED: "Plan created successfully",
    PLAN_UPDATED: "Plan updated successfully",
    PLAN_NOT_FOUND: "Plan not found",
    PLAN_LIST: "Plan List",
    CUSTOMER_ADDED: "Customer added successfully",
    CUSTOMER_ALREADY_PRESENT: "Customer already present",

    PLAN_DELETED: "Plan deleted successfully",

    
    DELETED: 'Successfully deleted.',
    UPDATED: 'Successfully updated.',
    ALREADY_EXISTS: 'Already exists.',
    CREATED: 'Successfully created.',
    LIST: 'List retrieved successfully.',
    DETAILS: 'Details retrieved successfully.',
    STATUS: 'Status updated successfully.',

}
